spring.application.name=api-challenge

# Configurações de conexão do H2
spring.datasource.url=jdbc:h2:mem:meubanco
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar o console web do H2 para acessar pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console